# Custom Language File for Launcher Customizer

[ejs.app]
title = "【Re:pg】RPG"

[ejs.landing]
mediaGitHubURL = "https://repgminecraft.creatorlink.net/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Read_Youtube"
mediaDiscordURL = "#"
mediaSoopURL = "https://ch.sooplive.co.kr/aass7978"
mediaChzzkURL = "https://chzzk.naver.com/live/77172c972f3db828c970e9b63a40ae21"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/Re-pg"
supportLink = "https://github.com/CustomLauncherLab/Re-pg/issues"

[ejs.welcome]
welcomeHeader = "【Re:pg】RPG"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."